# Generated by Django 2.2.3 on 2020-03-07 20:51

from django.db import migrations, models
import fooodie.models


class Migration(migrations.Migration):

    dependencies = [
        ('fooodie', '0002_auto_20200307_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=fooodie.models.get_upload_filename),
        ),
    ]
